id = "renpy"
name = "Ren'Py"
description = "Ren'Py language support (syntax + language server)."
version = "0.1.0"
schema_version = 1
authors = ["rdelacrz"]
repository = "https://github.com/rdelacrz/zed-language-renpy"

[language_servers.renpy-language-server]
name = "Ren'Py Language Server"
languages = ["Ren'Py"]

[grammars.renpy]
repository = "https://github.com/rdelacrz/zed-language-renpy/tree-sitter-renpy"
commit = "3d3ff1f1017ffcd9ea44d3cadf62b63f4b46dd26"

snippets = ["./snippets/renpy.json"]
